In [3]:
!pip3 install numpy

In [4]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np.__version__

'1.26.4'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
# num = np.array(<Iterable>)
num = np.array([11,22,33,44,55,66,77,88,99])
num

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [9]:
print(num)

[11 22 33 44 55 66 77 88 99]


In [10]:
# Indexation in numpy : start with 0
num[0]

11

In [11]:
num[6]# 77 

77

In [12]:
num[-1] # 99

99

In [13]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
np_arr = np.array(11) 
np_arr

array(11)

In [16]:
print(np_arr)

11


In [17]:
type(arr_from_list)

numpy.ndarray

In [18]:
# ndarray -> N Dimensional Array
print(type(arr_from_list)) # class <numpy.ndarray>

<class 'numpy.ndarray'>


In [19]:
# Properties [ndim]
# print("Hello World" , end = " ") -> end -> attribute
arr_from_list.ndim

1

In [20]:
# np_arr # 11
np_arr.ndim # 0

0

In [21]:
# 1D Array 
# Numpy -> An array object of arbitrary homogeneous items
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # Mixed Type [Upcasting]
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [22]:
type(arr_1d)

numpy.ndarray

In [23]:
arr_1d.dtype # property data type

dtype('<U64')

In [24]:
arr_1d.ndim

1

In [25]:
# 2D Array [2 Dimensional] [row * col] n*m (5,3)
# Numpy -> An array object of arbitrary homogeneous items
arr_2d = np.array([
    [11,22,33],
    ['a','b','c'],
    [True,False,True],
    ['learn','python','programming'],
    [9.99,11.11,12.99]
]) # Mixed Type [Heterogenous] 
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '12.99']]


In [26]:
type(arr_2d)

numpy.ndarray

In [27]:
arr_2d.ndim # property

2

In [30]:
# 3D [3 Dimensional] [Depth,row,col] (d*r*c) = Total Number of Elements
# 3 Depth , 3 Rows , 3 Cols = 27
arr_3d = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],

    [[1.1,2.1,3.1],
    [4.1,5.1,6.1],
    [7.1,8.1,9.1]],

    [[False,True,True],
    [True,False,True],
    [False,True,False]],
]) # 'upcasting' -> 'float'
arr_3d

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1.1, 2.1, 3.1],
        [4.1, 5.1, 6.1],
        [7.1, 8.1, 9.1]],

       [[0. , 1. , 1. ],
        [1. , 0. , 1. ],
        [0. , 1. , 0. ]]])

In [31]:
type(arr_3d)

numpy.ndarray

In [32]:
arr_3d.ndim # n- dimension [3D]

3

In [33]:
# 27 => 3*3*3
# 1D -> 3D 
arr_1d = np.array([1,2,3,4,5,6,7,8,9,'a','b','c','d','e','f','g','h','i',9,8,7,6,5,4,3,2,1])
arr_1d

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd',
       'e', 'f', 'g', 'h', 'i', '9', '8', '7', '6', '5', '4', '3', '2',
       '1'], dtype='<U11')

In [34]:
# 3D Shape [3,3,3] -> depth-> 3 , row -> 3 , cols -> 3
arr_1d.reshape(3,3,3)

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']],

       [['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']],

       [['9', '8', '7'],
        ['6', '5', '4'],
        ['3', '2', '1']]], dtype='<U11')

In [35]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [36]:
# 1D -> 2D
# 4*4 , 8*2, 2*8
arr_1d.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr_1d.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [39]:
arr_1d.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [40]:
# 3D -> 2*4*2 , 2*2*4, 1*4*4
arr_1d.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [41]:
arr_1d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [43]:
# 4D -> 2*2*2*2 # 3D[depth,rows,cols]
arr_4d = arr_1d.reshape(2,2,2,2) # 4D -> 2 depth of 3D
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [44]:
arr_4d.ndim # property

4

In [2]:
import numpy as np
# Specifying the Data Types [Upcasting]
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,99.99],
]) # upcast -> float
print(nested_list)

[[11.   22.  ]
 [33.   44.  ]
 [55.   66.  ]
 [77.   88.  ]
 [99.   99.99]]


In [3]:
nested_list.dtype

dtype('float64')

In [4]:
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,121],
]) # dtype attribute -> float
float_arr = np.array(nested_list , dtype = float)
float_arr

array([[ 11.,  22.],
       [ 33.,  44.],
       [ 55.,  66.],
       [ 77.,  88.],
       [ 99., 121.]])

In [5]:
# upcast ['str'] Vs upcast['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99.99,'121'],
]) # upcast['121'] us winning
float_arr = np.array(nested_list , dtype = float) # external force
float_arr

array([[ 11.  ,  22.  ],
       [ 33.  ,  44.  ],
       [ 55.  ,  66.  ],
       [ 77.  ,  88.  ],
       [ 99.99, 121.  ]])

In [6]:
nested_list

array([['11', '22'],
       ['33', '44'],
       ['55', '66'],
       ['77', '88'],
       ['99.99', '121']], dtype='<U32')

In [8]:
nested_list

array([['11', '22'],
       ['33', '44'],
       ['55', '66'],
       ['77', '88'],
       ['99.99', 'k']], dtype='<U32')

In [9]:
# upcast ['int'] Vs upcast['bool']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [True,False],
]) # upcast [int]
float_arr = np.array(nested_list , dtype = float) # external force
float_arr

array([[11., 22.],
       [33., 44.],
       [55., 66.],
       [77., 88.],
       [ 1.,  0.]])

In [10]:
nested_list

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88],
       [ 1,  0]])

In [11]:
nested_list.dtype

dtype('int32')

In [12]:
nested_list.ndim # 2

2

In [13]:
nested_list.shape

(5, 2)

In [14]:
# size -> no. of elements within the n dimensional array
nested_list.size

10

In [15]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [16]:
arr_1d.ndim

1

In [17]:
arr_1d.size

16

In [18]:
arr_1d.shape

(16,)

In [19]:
arr_4d = arr_1d.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [20]:
arr_4d.ndim

4

In [21]:
arr_4d.shape

(2, 2, 2, 2)

In [22]:
arr_4d.dtype

dtype('int32')

In [23]:
arr_4d.size

16

In [26]:
# itemsize() -> ndarray.itemsize attribute -> Memory Size of each elements (in Bytes)
# Homogenous Numpy Array
arr_int = np.array([1,2,3,4,5,6,7,8,9,11,15,21,77,99] , dtype = int)
print(arr_int.itemsize, "bytes")

4 bytes


In [27]:
arr_float = np.array([1,2,3,4,5,6,7,8,9,11,15,21,77,99] , dtype = float)
print(arr_float)
print(arr_float.itemsize, "bytes")

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 11. 15. 21. 77. 99.]
8 bytes


In [28]:
arr_str = np.array(['Coding','Python','Programming','Numpy','Array'] , dtype = str)
print(arr_str)
print(arr_str.itemsize , "bytes")

['Coding' 'Python' 'Programming' 'Numpy' 'Array']
44 bytes


In [29]:
arr_str = np.array(['Coding','Python','Java','Array'] , dtype = str)
print(arr_str)
print(arr_str.itemsize , "bytes") # 6 * 4 bytes ['each char'] = 24

['Coding' 'Python' 'Java' 'Array']
24 bytes


In [30]:
# ndarray.data # 'Memory Location' -> memory View
arr = np.array([11,22,33,44,55,66,77])
print("Data Buffer: " , arr.data) # Memory Address
print("Type of Buffer" , type(arr.data)) # 'Memory View'

Data Buffer:  <memory at 0x000002434073B700>
Type of Buffer <class 'memoryview'>


In [31]:
# Indexing , slicing , Operations on numpy array
arr_1d = np.array([11,22,33,44,55])
print(arr_1d[2]) # 33
print(arr_1d[-2]) # 44
print(arr_1d[-5]) # 11
# print(arr_1d[5]) # Index Error: Out of Range
print(arr_1d[0]) # 11

33
44
11
11


In [33]:
# Shape of 3D Array (2,3,4) -> 2(depth),3(rows),4(cols)
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
# indexing[depth,row,col]
print(arr_3d[-1,2,3]) # 88
print(arr_3d[-2,-3,-4]) # 11
# print(arr_3d[0,3,2]) # Error
# print(arr_3d[-2,0,4]) # Error
print(arr_3d[1,2,-3]) # 44
print(arr_3d[0,-1,-1]) # 77
print(arr_3d[-2,1,-4]) # 22
print(arr_3d[0,-3,3]) # 44

88
11
44
77
22
44


In [34]:
# Slicing[Start = 0 , Stop = length [Exclusive], Step = 1 [default]]
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
print(arr_1d[-3:]) # [77,88,99]
print(arr_1d[-3::-1]) # [77,66...11]
print(arr_1d[-3:9:-1]) # []
print(arr_1d[-3:-6:-1]) # [77,66,55]
print(arr_1d[-3:0:-1]) # [77,66....22]
print(arr_1d[5:9:2]) # [66,88]
print(arr_1d[5:4:2]) # []
print(arr_1d[5:4:-2]) # [66]
print(arr_1d[8:0:-2]) # [99,77,55,33]
print(arr_1d[-4::-2]) # [66,44,22]
print(arr_1d[3:8:-3]) # []
print(arr_1d[5:11:2]) # [66,88]

[77 88 99]
[77 66 55 44 33 22 11]
[]
[77 66 55]
[77 66 55 44 33 22]
[66 88]
[]
[66]
[99 77 55 33]
[66 44 22]
[]
[66 88]


In [35]:
# Slicing 2D [Start,Stop,Step]-> arr_2d [row_slicing , col_slicing] (4,5) 
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[1:3, 2:4]) # [[5 7] [6  8]]

[[5 7]
 [6 8]]


In [36]:
print(arr_2d[-3::1, 3::-1]) # 

[[7 5 3 1]
 [8 6 4 2]
 [2 3 4 5]]


In [37]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[3::-2 , 1:4:3]) # [[4][3]]

[[4]
 [3]]


In [38]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[2:5 , 2:5:-2]) # []

[]


In [39]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[2:5 , 2:5:2]) # [[6 0] [3 1]]

[[6 0]
 [3 1]]


In [40]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[: , ::-2]) 

[[5 3 1]
 [9 5 1]
 [0 6 2]
 [1 3 5]]


In [41]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[::-1 , ::-1]) # row in reverse , and col in reverse
# row in reverse
# [5,4,3,2,1]
# [2,4,6,8,0]
# [1,3,5,7,9]
# [1,2,3,4,5]
# col reverse wrt to row in reverse [right to left]
# [1,2,3,4,5]
# [0,8,6,4,2]
# [9,7,5,3,1]
# [5,4,3,2,1]

[[1 2 3 4 5]
 [0 8 6 4 2]
 [9 7 5 3 1]
 [5 4 3 2 1]]


In [42]:
# slicing in 3D Array [depth , row , col]
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
arr_3d[:,:,::-1] # Both depth including all rows but cols reversed

array([[[44, 33, 22, 11],
        [88, 66, 44, 22],
        [77, 55, 33, 11]],

       [[99, 88, 77, 66],
        [99, 77, 55, 11],
        [88, 66, 44, 22]]])

In [43]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
arr_3d[1::2, 0:3:2, ::-3]

array([[[99, 66],
        [88, 22]]])

In [44]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
print(arr_3d[-2,2,0]) # 11
arr_3d[-2: , -1: , 0:3:2] # last row of both depth

11


array([[[11, 55]],

       [[22, 66]]])

In [45]:
# SELECT * FROM TABLENAME WHERE = <Apply Filter>
# Masking -> Uses a boolean array of the same shape to filter the original array
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,True,False,False,True,False,True,False,True])
print(arr_1d[mask_arr]) # Filtering on the numpy array

[11 22 55 77 99]


In [46]:
arr_1d.shape

(9,)

In [47]:
mask_arr.shape

(9,)

In [48]:
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,True,False,False,True,False,True])
print(arr_1d.shape)
print(mask_arr.shape)

(9,)
(7,)


In [51]:
# arr_2d [Masking]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])
mask_2d = np.array([
    [True,True,False,False,True],
    [True,False,True,True,True],
    [True,False,False,False,False],
    [True,False,False,True,True]
])
# Final Result -> 1D [Flatten Up]
arr_2d[mask_2d]

array([1, 2, 5, 1, 5, 7, 9, 2, 5, 2, 1])

In [52]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
mask_3d = np.array([
    [[True,True,False,False],
     [True,False,False,False],
     [True,False,True,True],],
    
    [[False,True,False,True],
     [True,True,True,True],
     [False,False,False,False],]
])
arr_3d[mask_3d] # flatten up

array([11, 22, 22, 11, 55, 77, 77, 99, 11, 55, 77, 99])

In [53]:
# Ellipsis [...] -> Used Only Once in a slicing -> 3D Matrix
# 3D [2,5,2]
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...] # arr_3d[:,:,:]

array([[[ 11,  22],
        [ 33,  44],
        [ 55,  66],
        [ 77,  88],
        [ 99, 110]],

       [[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]]])

In [54]:
# Ellipsis [...] -> Used Only Once in a slicing -> 3D Matrix
# 3D [2,5,2]
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...,1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [55]:
arr_3d[:,:,1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [57]:
arr_3d.shape

(2, 5, 2)

In [58]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[:,0,...] # (depth,rows,cols)

array([[11, 22],
       [ 1,  2]])

In [59]:
arr_3d[:,0,:] # (depth,rows,cols)

array([[11, 22],
       [ 1,  2]])

In [60]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...,-1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [61]:
arr_3d[:,:,-1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [62]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[0,...] # (depth,rows,cols)

array([[ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88],
       [ 99, 110]])

In [63]:
arr_3d[0,:,:] # (depth,rows,cols)

array([[ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88],
       [ 99, 110]])

In [65]:
# Operations on Array
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([7,9,11,17,21,29,41,77,91])

print(a.shape)
print(b.shape)

(9,)
(9,)


In [66]:
# Addition
print("Numpy Array Addition: ")
a+b

Numpy Array Addition: 


array([ 18,  31,  44,  61,  76,  95, 118, 165, 190])

In [67]:
# Subtractions
print("Numpy Array Subtraction: ")
a-b

Numpy Array Subtraction: 


array([ 4, 13, 22, 27, 34, 37, 36, 11,  8])

In [68]:
# Multiplications
print("Numpy Array Multiplication: ")
a*b

Numpy Array Multiplication: 


array([  77,  198,  363,  748, 1155, 1914, 3157, 6776, 9009])

In [69]:
# Divisions
print("Numpy Array Divisions: ")
a/b

Numpy Array Divisions: 


array([1.57142857, 2.44444444, 3.        , 2.58823529, 2.61904762,
       2.27586207, 1.87804878, 1.14285714, 1.08791209])

In [70]:
# Floor Divisions
print("Numpy Array Floor Division: ")
a//b

Numpy Array Floor Division: 


array([1, 2, 3, 2, 2, 2, 1, 1, 1])

In [71]:
# Modulus 
print("Numpy Array Modulus: ")
a%b

Numpy Array Modulus: 


array([ 4,  4,  0, 10, 13,  8, 36, 11,  8])

In [72]:
# Exponentiations 
print("Numpy Array Exponent: ")
a ** 2

Numpy Array Exponent: 


array([ 121,  484, 1089, 1936, 3025, 4356, 5929, 7744, 9801])

In [73]:
# Exponentiations 
print("Numpy Array Exponent: ")
b ** 2

Numpy Array Exponent: 


array([  49,   81,  121,  289,  441,  841, 1681, 5929, 8281])

In [74]:
# Operations on Array [Unequal shape] -> Won't perform the operations
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([7,9,11,17,21,29,41])

print(a.shape)
print(b.shape)

(9,)
(7,)


In [76]:
# # Operations on 2D Array 
A = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]
])
B = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]
])
print(A.shape)
print(B.shape)

(5, 2)
(5, 2)


In [78]:
A+B

array([[ 12,  24],
       [ 36,  48],
       [ 60,  72],
       [ 84,  96],
       [108, 120]])

In [79]:
A-B

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [80]:
# Transposing an Array : Converting rows into coloumns and vice-versa. [Square Matrix]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
print("Original Array: \n", arr_2d)

Original Array: 
 [[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [11 15 17 19 21]]


In [81]:
print("Transposed Array: \n", arr_2d.transpose())

Transposed Array: 
 [[11 99 11 22 11]
 [22 88 33 44 15]
 [33 77 55 66 17]
 [44 66 77 88 19]
 [55 55 99 10 21]]


In [82]:
print("Transposed Array: \n", arr_2d.T)

Transposed Array: 
 [[11 99 11 22 11]
 [22 88 33 44 15]
 [33 77 55 66 17]
 [44 66 77 88 19]
 [55 55 99 10 21]]
