In [3]:
!pip3 install numpy

In [4]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np.__version__

'1.26.4'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
# num = np.array(<Iterable>)
num = np.array([11,22,33,44,55,66,77,88,99])
num

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [9]:
print(num)

[11 22 33 44 55 66 77 88 99]


In [10]:
# Indexation in numpy : start with 0
num[0]

11

In [11]:
num[6]# 77 

77

In [12]:
num[-1] # 99

99

In [13]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
np_arr = np.array(11) 
np_arr

array(11)

In [16]:
print(np_arr)

11


In [17]:
type(arr_from_list)

numpy.ndarray

In [18]:
# ndarray -> N Dimensional Array
print(type(arr_from_list)) # class <numpy.ndarray>

<class 'numpy.ndarray'>


In [19]:
# Properties [ndim]
# print("Hello World" , end = " ") -> end -> attribute
arr_from_list.ndim

1

In [20]:
# np_arr # 11
np_arr.ndim # 0

0

In [21]:
# 1D Array 
# Numpy -> An array object of arbitrary homogeneous items
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # Mixed Type [Upcasting]
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [22]:
type(arr_1d)

numpy.ndarray

In [23]:
arr_1d.dtype # property data type

dtype('<U64')

In [24]:
arr_1d.ndim

1

In [25]:
# 2D Array [2 Dimensional] [row * col] n*m (5,3)
# Numpy -> An array object of arbitrary homogeneous items
arr_2d = np.array([
    [11,22,33],
    ['a','b','c'],
    [True,False,True],
    ['learn','python','programming'],
    [9.99,11.11,12.99]
]) # Mixed Type [Heterogenous] 
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '12.99']]


In [26]:
type(arr_2d)

numpy.ndarray

In [27]:
arr_2d.ndim # property

2

In [30]:
# 3D [3 Dimensional] [Depth,row,col] (d*r*c) = Total Number of Elements
# 3 Depth , 3 Rows , 3 Cols = 27
arr_3d = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],

    [[1.1,2.1,3.1],
    [4.1,5.1,6.1],
    [7.1,8.1,9.1]],

    [[False,True,True],
    [True,False,True],
    [False,True,False]],
]) # 'upcasting' -> 'float'
arr_3d

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1.1, 2.1, 3.1],
        [4.1, 5.1, 6.1],
        [7.1, 8.1, 9.1]],

       [[0. , 1. , 1. ],
        [1. , 0. , 1. ],
        [0. , 1. , 0. ]]])

In [31]:
type(arr_3d)

numpy.ndarray

In [32]:
arr_3d.ndim # n- dimension [3D]

3

In [33]:
# 27 => 3*3*3
# 1D -> 3D 
arr_1d = np.array([1,2,3,4,5,6,7,8,9,'a','b','c','d','e','f','g','h','i',9,8,7,6,5,4,3,2,1])
arr_1d

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd',
       'e', 'f', 'g', 'h', 'i', '9', '8', '7', '6', '5', '4', '3', '2',
       '1'], dtype='<U11')

In [34]:
# 3D Shape [3,3,3] -> depth-> 3 , row -> 3 , cols -> 3
arr_1d.reshape(3,3,3)

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']],

       [['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']],

       [['9', '8', '7'],
        ['6', '5', '4'],
        ['3', '2', '1']]], dtype='<U11')

In [35]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [36]:
# 1D -> 2D
# 4*4 , 8*2, 2*8
arr_1d.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr_1d.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [39]:
arr_1d.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [40]:
# 3D -> 2*4*2 , 2*2*4, 1*4*4
arr_1d.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [41]:
arr_1d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [43]:
# 4D -> 2*2*2*2 # 3D[depth,rows,cols]
arr_4d = arr_1d.reshape(2,2,2,2) # 4D -> 2 depth of 3D
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [44]:
arr_4d.ndim # property

4

In [2]:
import numpy as np
# Specifying the Data Types [Upcasting]
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,99.99],
]) # upcast -> float
print(nested_list)

[[11.   22.  ]
 [33.   44.  ]
 [55.   66.  ]
 [77.   88.  ]
 [99.   99.99]]


In [3]:
nested_list.dtype

dtype('float64')

In [4]:
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,121],
]) # dtype attribute -> float
float_arr = np.array(nested_list , dtype = float)
float_arr

array([[ 11.,  22.],
       [ 33.,  44.],
       [ 55.,  66.],
       [ 77.,  88.],
       [ 99., 121.]])

In [5]:
# upcast ['str'] Vs upcast['float']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99.99,'121'],
]) # upcast['121'] us winning
float_arr = np.array(nested_list , dtype = float) # external force
float_arr

array([[ 11.  ,  22.  ],
       [ 33.  ,  44.  ],
       [ 55.  ,  66.  ],
       [ 77.  ,  88.  ],
       [ 99.99, 121.  ]])

In [6]:
nested_list

array([['11', '22'],
       ['33', '44'],
       ['55', '66'],
       ['77', '88'],
       ['99.99', '121']], dtype='<U32')

In [8]:
nested_list

array([['11', '22'],
       ['33', '44'],
       ['55', '66'],
       ['77', '88'],
       ['99.99', 'k']], dtype='<U32')

In [9]:
# upcast ['int'] Vs upcast['bool']
nested_list = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [True,False],
]) # upcast [int]
float_arr = np.array(nested_list , dtype = float) # external force
float_arr

array([[11., 22.],
       [33., 44.],
       [55., 66.],
       [77., 88.],
       [ 1.,  0.]])

In [10]:
nested_list

array([[11, 22],
       [33, 44],
       [55, 66],
       [77, 88],
       [ 1,  0]])

In [11]:
nested_list.dtype

dtype('int32')

In [12]:
nested_list.ndim # 2

2

In [13]:
nested_list.shape

(5, 2)

In [14]:
# size -> no. of elements within the n dimensional array
nested_list.size

10

In [15]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [16]:
arr_1d.ndim

1

In [17]:
arr_1d.size

16

In [18]:
arr_1d.shape

(16,)

In [19]:
arr_4d = arr_1d.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [20]:
arr_4d.ndim

4

In [21]:
arr_4d.shape

(2, 2, 2, 2)

In [22]:
arr_4d.dtype

dtype('int32')

In [23]:
arr_4d.size

16

In [26]:
# itemsize() -> ndarray.itemsize attribute -> Memory Size of each elements (in Bytes)
# Homogenous Numpy Array
arr_int = np.array([1,2,3,4,5,6,7,8,9,11,15,21,77,99] , dtype = int)
print(arr_int.itemsize, "bytes")

4 bytes


In [27]:
arr_float = np.array([1,2,3,4,5,6,7,8,9,11,15,21,77,99] , dtype = float)
print(arr_float)
print(arr_float.itemsize, "bytes")

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 11. 15. 21. 77. 99.]
8 bytes


In [28]:
arr_str = np.array(['Coding','Python','Programming','Numpy','Array'] , dtype = str)
print(arr_str)
print(arr_str.itemsize , "bytes")

['Coding' 'Python' 'Programming' 'Numpy' 'Array']
44 bytes


In [29]:
arr_str = np.array(['Coding','Python','Java','Array'] , dtype = str)
print(arr_str)
print(arr_str.itemsize , "bytes") # 6 * 4 bytes ['each char'] = 24

['Coding' 'Python' 'Java' 'Array']
24 bytes


In [30]:
# ndarray.data # 'Memory Location' -> memory View
arr = np.array([11,22,33,44,55,66,77])
print("Data Buffer: " , arr.data) # Memory Address
print("Type of Buffer" , type(arr.data)) # 'Memory View'

Data Buffer:  <memory at 0x000002434073B700>
Type of Buffer <class 'memoryview'>


In [31]:
# Indexing , slicing , Operations on numpy array
arr_1d = np.array([11,22,33,44,55])
print(arr_1d[2]) # 33
print(arr_1d[-2]) # 44
print(arr_1d[-5]) # 11
# print(arr_1d[5]) # Index Error: Out of Range
print(arr_1d[0]) # 11

33
44
11
11


In [33]:
# Shape of 3D Array (2,3,4) -> 2(depth),3(rows),4(cols)
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
# indexing[depth,row,col]
print(arr_3d[-1,2,3]) # 88
print(arr_3d[-2,-3,-4]) # 11
# print(arr_3d[0,3,2]) # Error
# print(arr_3d[-2,0,4]) # Error
print(arr_3d[1,2,-3]) # 44
print(arr_3d[0,-1,-1]) # 77
print(arr_3d[-2,1,-4]) # 22
print(arr_3d[0,-3,3]) # 44

88
11
44
77
22
44


In [34]:
# Slicing[Start = 0 , Stop = length [Exclusive], Step = 1 [default]]
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
print(arr_1d[-3:]) # [77,88,99]
print(arr_1d[-3::-1]) # [77,66...11]
print(arr_1d[-3:9:-1]) # []
print(arr_1d[-3:-6:-1]) # [77,66,55]
print(arr_1d[-3:0:-1]) # [77,66....22]
print(arr_1d[5:9:2]) # [66,88]
print(arr_1d[5:4:2]) # []
print(arr_1d[5:4:-2]) # [66]
print(arr_1d[8:0:-2]) # [99,77,55,33]
print(arr_1d[-4::-2]) # [66,44,22]
print(arr_1d[3:8:-3]) # []
print(arr_1d[5:11:2]) # [66,88]

[77 88 99]
[77 66 55 44 33 22 11]
[]
[77 66 55]
[77 66 55 44 33 22]
[66 88]
[]
[66]
[99 77 55 33]
[66 44 22]
[]
[66 88]


In [35]:
# Slicing 2D [Start,Stop,Step]-> arr_2d [row_slicing , col_slicing] (4,5) 
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[1:3, 2:4]) # [[5 7] [6  8]]

[[5 7]
 [6 8]]


In [36]:
print(arr_2d[-3::1, 3::-1]) # 

[[7 5 3 1]
 [8 6 4 2]
 [2 3 4 5]]


In [37]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[3::-2 , 1:4:3]) # [[4][3]]

[[4]
 [3]]


In [38]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[2:5 , 2:5:-2]) # []

[]


In [39]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[2:5 , 2:5:2]) # [[6 0] [3 1]]

[[6 0]
 [3 1]]


In [40]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[: , ::-2]) 

[[5 3 1]
 [9 5 1]
 [0 6 2]
 [1 3 5]]


In [41]:
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1],
])
print(arr_2d[::-1 , ::-1]) # row in reverse , and col in reverse
# row in reverse
# [5,4,3,2,1]
# [2,4,6,8,0]
# [1,3,5,7,9]
# [1,2,3,4,5]
# col reverse wrt to row in reverse [right to left]
# [1,2,3,4,5]
# [0,8,6,4,2]
# [9,7,5,3,1]
# [5,4,3,2,1]

[[1 2 3 4 5]
 [0 8 6 4 2]
 [9 7 5 3 1]
 [5 4 3 2 1]]


In [42]:
# slicing in 3D Array [depth , row , col]
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
arr_3d[:,:,::-1] # Both depth including all rows but cols reversed

array([[[44, 33, 22, 11],
        [88, 66, 44, 22],
        [77, 55, 33, 11]],

       [[99, 88, 77, 66],
        [99, 77, 55, 11],
        [88, 66, 44, 22]]])

In [43]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
arr_3d[1::2, 0:3:2, ::-3]

array([[[99, 66],
        [88, 22]]])

In [44]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
print(arr_3d[-2,2,0]) # 11
arr_3d[-2: , -1: , 0:3:2] # last row of both depth

11


array([[[11, 55]],

       [[22, 66]]])

In [45]:
# SELECT * FROM TABLENAME WHERE = <Apply Filter>
# Masking -> Uses a boolean array of the same shape to filter the original array
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,True,False,False,True,False,True,False,True])
print(arr_1d[mask_arr]) # Filtering on the numpy array

[11 22 55 77 99]


In [46]:
arr_1d.shape

(9,)

In [47]:
mask_arr.shape

(9,)

In [48]:
arr_1d = np.array([11,22,33,44,55,66,77,88,99])
mask_arr = np.array([True,True,False,False,True,False,True])
print(arr_1d.shape)
print(mask_arr.shape)

(9,)
(7,)


In [51]:
# arr_2d [Masking]
arr_2d = np.array([
    [1,2,3,4,5],
    [1,3,5,7,9],
    [2,4,6,8,0],
    [5,4,3,2,1]
])
mask_2d = np.array([
    [True,True,False,False,True],
    [True,False,True,True,True],
    [True,False,False,False,False],
    [True,False,False,True,True]
])
# Final Result -> 1D [Flatten Up]
arr_2d[mask_2d]

array([1, 2, 5, 1, 5, 7, 9, 2, 5, 2, 1])

In [52]:
arr_3d = np.array([
    [[11,22,33,44],
     [22,44,66,88],
     [11,33,55,77],],
    
    [[66,77,88,99],
     [11,55,77,99],
     [22,44,66,88],]
])
mask_3d = np.array([
    [[True,True,False,False],
     [True,False,False,False],
     [True,False,True,True],],
    
    [[False,True,False,True],
     [True,True,True,True],
     [False,False,False,False],]
])
arr_3d[mask_3d] # flatten up

array([11, 22, 22, 11, 55, 77, 77, 99, 11, 55, 77, 99])

In [53]:
# Ellipsis [...] -> Used Only Once in a slicing -> 3D Matrix
# 3D [2,5,2]
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...] # arr_3d[:,:,:]

array([[[ 11,  22],
        [ 33,  44],
        [ 55,  66],
        [ 77,  88],
        [ 99, 110]],

       [[  1,   2],
        [  3,   4],
        [  5,   6],
        [  7,   8],
        [  9,  10]]])

In [54]:
# Ellipsis [...] -> Used Only Once in a slicing -> 3D Matrix
# 3D [2,5,2]
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...,1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [55]:
arr_3d[:,:,1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [57]:
arr_3d.shape

(2, 5, 2)

In [58]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[:,0,...] # (depth,rows,cols)

array([[11, 22],
       [ 1,  2]])

In [59]:
arr_3d[:,0,:] # (depth,rows,cols)

array([[11, 22],
       [ 1,  2]])

In [60]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[...,-1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [61]:
arr_3d[:,:,-1] # (depth,rows,cols)

array([[ 22,  44,  66,  88, 110],
       [  2,   4,   6,   8,  10]])

In [62]:
arr_3d = np.array([
    [[11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110],],
    
    [[1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10],]
])
arr_3d[0,...] # (depth,rows,cols)

array([[ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88],
       [ 99, 110]])

In [63]:
arr_3d[0,:,:] # (depth,rows,cols)

array([[ 11,  22],
       [ 33,  44],
       [ 55,  66],
       [ 77,  88],
       [ 99, 110]])

In [65]:
# Operations on Array
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([7,9,11,17,21,29,41,77,91])

print(a.shape)
print(b.shape)

(9,)
(9,)


In [66]:
# Addition
print("Numpy Array Addition: ")
a+b

Numpy Array Addition: 


array([ 18,  31,  44,  61,  76,  95, 118, 165, 190])

In [67]:
# Subtractions
print("Numpy Array Subtraction: ")
a-b

Numpy Array Subtraction: 


array([ 4, 13, 22, 27, 34, 37, 36, 11,  8])

In [68]:
# Multiplications
print("Numpy Array Multiplication: ")
a*b

Numpy Array Multiplication: 


array([  77,  198,  363,  748, 1155, 1914, 3157, 6776, 9009])

In [69]:
# Divisions
print("Numpy Array Divisions: ")
a/b

Numpy Array Divisions: 


array([1.57142857, 2.44444444, 3.        , 2.58823529, 2.61904762,
       2.27586207, 1.87804878, 1.14285714, 1.08791209])

In [70]:
# Floor Divisions
print("Numpy Array Floor Division: ")
a//b

Numpy Array Floor Division: 


array([1, 2, 3, 2, 2, 2, 1, 1, 1])

In [71]:
# Modulus 
print("Numpy Array Modulus: ")
a%b

Numpy Array Modulus: 


array([ 4,  4,  0, 10, 13,  8, 36, 11,  8])

In [72]:
# Exponentiations 
print("Numpy Array Exponent: ")
a ** 2

Numpy Array Exponent: 


array([ 121,  484, 1089, 1936, 3025, 4356, 5929, 7744, 9801])

In [73]:
# Exponentiations 
print("Numpy Array Exponent: ")
b ** 2

Numpy Array Exponent: 


array([  49,   81,  121,  289,  441,  841, 1681, 5929, 8281])

In [74]:
# Operations on Array [Unequal shape] -> Won't perform the operations
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array([7,9,11,17,21,29,41])

print(a.shape)
print(b.shape)

(9,)
(7,)


In [76]:
# # Operations on 2D Array 
A = np.array([
    [11,22],
    [33,44],
    [55,66],
    [77,88],
    [99,110]
])
B = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8],
    [9,10]
])
print(A.shape)
print(B.shape)

(5, 2)
(5, 2)


In [78]:
A+B

array([[ 12,  24],
       [ 36,  48],
       [ 60,  72],
       [ 84,  96],
       [108, 120]])

In [79]:
A-B

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [80]:
# Transposing an Array : Converting rows into coloumns and vice-versa. [Square Matrix]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
print("Original Array: \n", arr_2d)

Original Array: 
 [[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [11 15 17 19 21]]


In [81]:
print("Transposed Array: \n", arr_2d.transpose())

Transposed Array: 
 [[11 99 11 22 11]
 [22 88 33 44 15]
 [33 77 55 66 17]
 [44 66 77 88 19]
 [55 55 99 10 21]]


In [82]:
print("Transposed Array: \n", arr_2d.T)

Transposed Array: 
 [[11 99 11 22 11]
 [22 88 33 44 15]
 [33 77 55 66 17]
 [44 66 77 88 19]
 [55 55 99 10 21]]


# Sorting An Array:
##### Sorting means arranging an elements in ascending (default) or descending order

In [1]:
import numpy as np
arr_1d = np.array([77,11,22,55,33,44,99,66,88])
print(arr_1d)
print(np.sort(arr_1d))

[77 11 22 55 33 44 99 66 88]
[11 22 33 44 55 66 77 88 99]


In [2]:
# Descending Order using slicing [::-1]
print(np.sort(arr_1d)[::-1]) 

[99 88 77 66 55 44 33 22 11]


In [3]:
# Axis = 0 [Horizontal Axis][Rows] & Axis = 1 [Vertical Axis][Cols]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.sort(arr_2d , axis = 0)

array([[11, 15, 17, 19, 10],
       [11, 22, 33, 44, 21],
       [11, 33, 55, 66, 55],
       [22, 44, 66, 77, 55],
       [99, 88, 77, 88, 99]])

In [4]:
# axis = 1 [Vertical Axis] [Col]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.sort(arr_2d , axis = 1)

array([[11, 22, 33, 44, 55],
       [55, 66, 77, 88, 99],
       [11, 33, 55, 77, 99],
       [10, 22, 44, 66, 88],
       [11, 15, 17, 19, 21]])

In [5]:
# argsort [Indexing Sort]
arr_1d = np.array([55,11,44,33,22])
pos_arr = np.argsort(arr_1d)
print(arr_1d)
print(pos_arr)

[55 11 44 33 22]
[1 4 3 2 0]


In [9]:
# Indexing 
arr_1d[1] # 11

11

In [10]:
arr_1d[4] # 22

22

In [11]:
arr_1d[3] # 33

33

In [6]:
# Returns the indices that would sort an array. [argsort]
arr_1d[pos_arr]

array([11, 22, 33, 44, 55])

In [7]:
# argsort [Indexing Sort] [Descending]
arr_1d = np.array([55,11,44,33,22])
pos_arr = np.argsort(arr_1d)[::-1]
print(arr_1d)
print(pos_arr)

[55 11 44 33 22]
[0 2 3 4 1]


In [8]:
arr_1d[pos_arr] # Descending

array([55, 44, 33, 22, 11])

In [12]:
# argsort -> 2D Matrix
# axis = 1 [Vertical] [Col]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
print(arr_2d)
print(np.argsort(arr_2d , axis = 1))

[[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [11 15 17 19 21]]
[[0 1 2 3 4]
 [4 3 2 1 0]
 [0 1 2 3 4]
 [4 0 1 2 3]
 [0 1 2 3 4]]


In [13]:
# argsort -> 2D Matrix
# axis = 0 [Horizontal] [Row]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
print(arr_2d)
print(np.argsort(arr_2d , axis = 0))

[[11 22 33 44 55]
 [99 88 77 66 55]
 [11 33 55 77 99]
 [22 44 66 88 10]
 [11 15 17 19 21]]
[[0 4 4 4 3]
 [2 0 0 0 4]
 [4 2 2 1 0]
 [3 3 3 2 1]
 [1 1 1 3 2]]


In [16]:
# Concatenating an Array: It means joining the array either row wise or column wise
X = np.array([11,22,33,44,55])
Y = np.array([66,77,88,99])
Z = np.array([1,2,3,4,5,6,7,8,9])
print(np.concatenate((X,Y,Z)))

[11 22 33 44 55 66 77 88 99  1  2  3  4  5  6  7  8  9]


In [17]:
print(np.concatenate((Y,X,Z)))

[66 77 88 99 11 22 33 44 55  1  2  3  4  5  6  7  8  9]


In [18]:
print(np.concatenate((Z,X,Y)))

[ 1  2  3  4  5  6  7  8  9 11 22 33 44 55 66 77 88 99]


In [19]:
# Concatenating on 2D Matrix
arr_2dA = np.array([
    [11,22,33],
    [44,55,66],
    [77,88,99],
]) # shape(3,3)

arr_2dB = np.array([
    [11,22],
    [44,55],
    [77,88],
]) # shape(3,2)

arr_2dC = np.array([
    [11,22,33],
    [44,55,66],
]) # shape(2,3)

In [22]:
print(np.concatenate((arr_2dA , arr_2dB) , axis = 1)) # Vertically Append [Col-wise]

[[11 22 33 11 22]
 [44 55 66 44 55]
 [77 88 99 77 88]]


In [24]:
print(np.concatenate((arr_2dA , arr_2dC) , axis = 0)) # Horizontal Append [Row-wise]

[[11 22 33]
 [44 55 66]
 [77 88 99]
 [11 22 33]
 [44 55 66]]


In [26]:
# arange(start,stop,step) 
for i in range(1,11):
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 

In [27]:
# arange(start,stop,step) 
# Reshape(shape)
arr = np.arange(2,21,2) # [2,4,6...20]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
# 10 elements -> 2D Matrix [2*5] [5*2]
arr_2d = arr.reshape(2,5)
arr_2d

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [30]:
# 10 elements -> 2D Matrix [2*5] [5*2]
arr_2d = arr.reshape(5,2)
arr_2d

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16],
       [18, 20]])

In [31]:
arr = np.arange(1,17,1) # [1,2,3,4....16]
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [33]:
# 16 elements -> 2D,3D,4D
arr_2d = arr.reshape(4,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
arr_2d = arr.reshape(8,2)
arr_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [35]:
arr_2d = arr.reshape(2,8)
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [37]:
arr_3d = arr_2d.reshape(2,4,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [38]:
arr_3d = arr_2d.reshape(2,2,4)
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [39]:
arr_3d = arr_2d.reshape(4,2,2)
arr_3d

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [40]:
arr_4d = arr_3d.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [41]:
arr_4d = arr_2d.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [43]:
arr_4d = arr.reshape(2,2,2,2)
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [44]:
# Flattening an array: n-dimensional to 1D Array
flatten_arr = arr_4d.reshape(-1)
flatten_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [45]:
# Flattening an array: n-dimensional to 1D Array
flatten_arr = arr_2d.reshape(-1)
flatten_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [46]:
flatten_arr = arr_3d.reshape(-1)
flatten_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [47]:
# Splitting an Array
arr = np.arange(2,21,2) # 10 elements [2,4,6...20]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
split_arr = np.split(arr , 5)
print(split_arr)

[array([2, 4]), array([6, 8]), array([10, 12]), array([14, 16]), array([18, 20])]


In [49]:
split_arr

[array([2, 4]),
 array([6, 8]),
 array([10, 12]),
 array([14, 16]),
 array([18, 20])]

In [51]:
# Splitting an Array
arr = np.arange(1,16,1) # 15 elements [1,2,3,4...15]
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [52]:
split_arr = np.split(arr , 3) 
print(split_arr)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]


In [54]:
for data in split_arr:
    print(data)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [56]:
# axis = 0 [Horizontal axis] [rows]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
split_arr = np.split(arr_2d, 5 , axis = 0)
split_arr

[array([[11, 22, 33, 44, 55]]),
 array([[99, 88, 77, 66, 55]]),
 array([[11, 33, 55, 77, 99]]),
 array([[22, 44, 66, 88, 10]]),
 array([[11, 15, 17, 19, 21]])]

In [57]:
for data in split_arr:
    print(data)

[[11 22 33 44 55]]
[[99 88 77 66 55]]
[[11 33 55 77 99]]
[[22 44 66 88 10]]
[[11 15 17 19 21]]


In [59]:
print(type(split_arr))

<class 'list'>


In [60]:
# axis = 1 [Vertical axis] [cols]
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
split_arr = np.split(arr_2d, 5 , axis = 1)
split_arr

[array([[11],
        [99],
        [11],
        [22],
        [11]]),
 array([[22],
        [88],
        [33],
        [44],
        [15]]),
 array([[33],
        [77],
        [55],
        [66],
        [17]]),
 array([[44],
        [66],
        [77],
        [88],
        [19]]),
 array([[55],
        [55],
        [99],
        [10],
        [21]])]

In [61]:
for data in split_arr:
    print(data)

[[11]
 [99]
 [11]
 [22]
 [11]]
[[22]
 [88]
 [33]
 [44]
 [15]]
[[33]
 [77]
 [55]
 [66]
 [17]]
[[44]
 [66]
 [77]
 [88]
 [19]]
[[55]
 [55]
 [99]
 [10]
 [21]]


In [62]:
# Statistical Operations on Array
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.mean(arr_2d)

45.52

In [63]:
# axis = 0 [horizontal Axis] [rows]
np.mean(arr_2d , axis = 0)

array([30.8, 40.4, 49.6, 58.8, 48. ])

In [64]:
(11+99+11+22+11)/5

30.8

In [66]:
(22+88+33+44+15)/5

40.4

In [67]:
# axis = 1 [Vertical Axis] [cols]
np.mean(arr_2d , axis = 1)

array([33. , 77. , 55. , 46. , 16.6])

In [68]:
(11+22+33+44+55)/5

33.0

In [69]:
# Median
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.median(arr_2d)

44.0

In [70]:
# axis = 0 [horizontal Axis] [rows]
np.median(arr_2d , axis = 0)

array([11., 33., 55., 66., 55.])

In [71]:
# axis = 1 [Vertical Axis] [cols]
np.median(arr_2d , axis = 1)

array([33., 77., 55., 44., 17.])

In [72]:
# standard deviation
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.std(arr_2d)

29.48236082812908

In [73]:
# axis = 0 [horizontal Axis] [rows]
np.std(arr_2d , axis = 0)

array([34.36509857, 25.75732905, 21.85040045, 24.65278889, 31.21538082])

In [74]:
# axis = 1 [Vertical Axis] [cols]
np.std(arr_2d , axis = 1)

array([15.55634919, 15.55634919, 31.11269837, 28.42534081,  3.44093011])

In [75]:
# Min / Max -> Return Smallest and the largest values respectively.
# Min
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.min(arr_2d) # 10

10

In [76]:
# axis = 0 [horizontal Axis] [rows]
np.min(arr_2d , axis = 0)

array([11, 15, 17, 19, 10])

In [77]:
# axis = 1 [Vertical Axis] [cols]
np.min(arr_2d , axis = 1)

array([11, 55, 11, 10, 11])

In [79]:
# Max
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.max(arr_2d) # 99

99

In [81]:
# axis = 0 [horizontal Axis] [rows]
np.max(arr_2d , axis = 0)

array([99, 88, 77, 88, 99])

In [82]:
# axis = 1 [Vertical Axis] [cols]
np.max(arr_2d , axis = 1)

array([55, 99, 99, 88, 21])

In [83]:
# Sum -> Calculating the total of each elements within the range
arr_2d = np.array([
    [11,22,33,44,55],
    [99,88,77,66,55],
    [11,33,55,77,99],
    [22,44,66,88,10],
    [11,15,17,19,21]
])
np.sum(arr_2d)

1138

In [84]:
# axis = 0 [horizontal Axis] [rows]
np.sum(arr_2d , axis = 0)

array([154, 202, 248, 294, 240])

In [85]:
# axis = 1 [Vertical Axis] [cols]
np.sum(arr_2d , axis = 1)

array([165, 385, 275, 230,  83])

In [86]:
# Other ways to Create Numpy Array.
np.zeros(11) # np.zeros(shape) 
# 1D array filled with zeros 0. <float>

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
# Return a new array of given shape and type, filled with zeros.
np.zeros(9, dtype = int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
# 2D Matrix
np.zeros((7,2) , dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [89]:
# 3D Matrix
np.zeros((2,3,2)) # default dtype - float

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [90]:
# 4D Matrix
np.zeros((2,2,2,2), dtype = bool) # 0 in bool -> False

array([[[[False, False],
         [False, False]],

        [[False, False],
         [False, False]]],


       [[[False, False],
         [False, False]],

        [[False, False],
         [False, False]]]])

In [91]:
# np.ones(shape) -> filled with 1.
# 3D Matrix
np.ones((2,3,4) , dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [92]:
# 3D Matrix
np.ones((2,3,4) , dtype = bool) # 1 in bool -> True

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [93]:
# np.full(shape, fill_value)
# return a new array of given shape and type, filled with `fill_value`
np.full(11, 9)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [94]:
# 2D Matrix
np.full((4,5), 11.1)

array([[11.1, 11.1, 11.1, 11.1, 11.1],
       [11.1, 11.1, 11.1, 11.1, 11.1],
       [11.1, 11.1, 11.1, 11.1, 11.1],
       [11.1, 11.1, 11.1, 11.1, 11.1]])

In [95]:
# 3D Matrix
np.full((2,4,3), 11+9j)

array([[[11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j]],

       [[11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j],
        [11.+9.j, 11.+9.j, 11.+9.j]]])

In [96]:
# 3D Matrix
np.full((2,4,3), 'abc')

array([[['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc']],

       [['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc'],
        ['abc', 'abc', 'abc']]], dtype='<U3')

In [97]:
# 3D Matrix
np.full((2,4,3), 'Python')

array([[['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python']],

       [['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python'],
        ['Python', 'Python', 'Python']]], dtype='<U6')

In [98]:
# Identity Matrix -> having digonal elements filled with 1 and other non-diagonal are filled with 0.
# np.identity() -> square matrix 
# np.eye() -> Rectangular/Square Matrix, k-factor
# 3*3 Matrix
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [100]:
# 3*3 Matrix
np.eye(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [102]:
# Rectangular Matrix
# m * n Matrix
np.eye(4,7, dtype=float)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [103]:
# Rectangular Matrix with k-factor
# m * n Matrix
np.eye(4,7,k=1,dtype=float)

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [104]:
# Rectangular Matrix with k-factor
# m * n Matrix
np.eye(4,7,k=2,dtype=float)

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [105]:
# Rectangular Matrix with k-factor
# m * n Matrix
np.eye(4,7,k=-1,dtype=float)

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [106]:
# Rectangular Matrix with k-factor
# m * n Matrix
np.eye(4,7,k=-2,dtype=float)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]])

In [107]:
# Square Matrix
np.eye(7, k = 0)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [108]:
# Square Matrix
np.eye(7, k = 1)

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [109]:
# Square Matrix
np.eye(7, k = 4)

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [110]:
# Square Matrix
np.eye(7, k = -5)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.]])

In [111]:
# Square Matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [112]:
# Return the identity array.
# The identity array is a square array with ones on the main diagonal.
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [116]:
# np.arange(start , stop, step)
np.arange(1,11,2) # odd numpy array [1,3,..9]

array([1, 3, 5, 7, 9])

In [117]:
np.arange(2,21,2) # Even Numpy Array [2,4...20]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [118]:
np.arange(1,15,-1) # []

array([], dtype=int32)

In [119]:
np.arange(15,0,-2) # [15,13,11...1]

array([15, 13, 11,  9,  7,  5,  3,  1])

In [120]:
# np.random -> shape()
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [121]:
# 1D Matrix
# np.random.random(shape) -> [0,1) -> Range
np.random.random(11)

array([0.3749287 , 0.9242952 , 0.1686759 , 0.77277538, 0.59295769,
       0.9331255 , 0.39123287, 0.42077007, 0.03007149, 0.62073985,
       0.76482758])

In [122]:
np.random.random(11).round(2)

array([0.5 , 0.17, 0.71, 0.98, 0.15, 0.32, 0.34, 0.21, 0.23, 0.89, 0.48])

In [123]:
# 2D Matrix 
np.random.random((5,3)).round(2)

array([[0.81, 0.37, 0.8 ],
       [0.67, 0.12, 0.81],
       [0.63, 0.  , 0.78],
       [0.84, 0.81, 0.82],
       [0.18, 0.08, 0.15]])

In [124]:
# 3D Matrix
# Return random integers from `low` (inclusive) to `high` (exclusive)
np.random.randint(100,1000,(2,4,3)) # [100,1000)

array([[[429, 831, 887],
        [999, 494, 432],
        [205, 428, 500],
        [506, 132, 677]],

       [[770, 827, 593],
        [105, 838, 954],
        [902, 767, 463],
        [882, 481, 275]]])

In [139]:
# linspace(start,stop,number of elements) # Evenly spaced data
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [126]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [127]:
1.94736842 - 1.47368421

0.47368421000000005

In [128]:
1.94736842 + 0.47368421

2.42105263

In [129]:
np.linspace(1,10,19)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [132]:
np.linspace(1,100,51)

array([  1.  ,   2.98,   4.96,   6.94,   8.92,  10.9 ,  12.88,  14.86,
        16.84,  18.82,  20.8 ,  22.78,  24.76,  26.74,  28.72,  30.7 ,
        32.68,  34.66,  36.64,  38.62,  40.6 ,  42.58,  44.56,  46.54,
        48.52,  50.5 ,  52.48,  54.46,  56.44,  58.42,  60.4 ,  62.38,
        64.36,  66.34,  68.32,  70.3 ,  72.28,  74.26,  76.24,  78.22,
        80.2 ,  82.18,  84.16,  86.14,  88.12,  90.1 ,  92.08,  94.06,
        96.04,  98.02, 100.  ])