In [1]:
# Scipy
import numpy as np
from scipy import stats

In [2]:
dir(stats)

['BootstrapMethod',
 'CensoredData',
 'ConstantInputWarning',
 'Covariance',
 'DegenerateDataWarning',
 'FitError',
 'MonteCarloMethod',
 'NearConstantInputWarning',
 'PermutationMethod',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_ansari_swilk_statistics',
 '_axis_nan_policy',
 '_biasedurn',
 '_binned_statistic',
 '_binomtest',
 '_boost',
 '_bws_test',
 '_censored_data',
 '_common',
 '_constants',
 '_continuous_distns',
 '_covariance',
 '_crosstab',
 '_discrete_distns',
 '_distn_infrastructure',
 '_distr_params',
 '_entropy',
 '_fit',
 '_hypotests',
 '_kde',
 '_ksstats',
 '_levy_stable',
 '_mannwhitneyu',
 '_morestats',
 '_mstats_basic',
 '_mstats_extras',
 '_multicomp',
 '_multivariate',
 '_mvn',
 '_odds_ratio',
 '_page_trend_test',
 '_qmc',
 '_qmc_cy',
 '_qmvnt',
 '_rcont',
 '_relative_risk',
 '_resampling',
 '_rvs_sampling',
 '_sampling',
 '_sensitivity_analysis',
 '_sobol',
 '_stats',

In [3]:
# Generate Data
np.random.seed(11)
data = np.random.normal(loc=50,scale=10,size=1000)
data

array([67.49454741, 47.13927003, 45.15434868, 23.46681441, 49.91715371,
       46.80368636, 44.63370638, 53.15402668, 54.21050716, 39.3439702 ,
       41.1376033 , 45.24266507, 56.8968231 , 55.61192176, 36.9445149 ,
       38.80524738, 57.36837391, 65.74634073, 49.68924912, 43.16553373,
       60.95629699, 46.90423363, 57.25752225, 65.49071633, 56.30079822,
       50.73493237, 57.32271354, 43.57424608, 48.21906825, 44.26045441,
       47.95624684, 45.135049  , 48.14224676, 46.19463583, 50.88977635,
       50.63671661, 52.96347108, 64.02771119, 34.53137432, 62.95618585,
       47.62749554, 37.67653793, 48.27580233, 50.91838375, 60.67558457,
       39.38365552, 52.17348208, 51.17819504, 33.15889107, 38.14244735,
       56.00102006, 56.95567255, 60.8771086 , 55.33821716, 53.95212013,
       51.22867529, 62.09101642, 41.56933899, 48.58106419, 53.85354138,
       34.22505691, 63.1094364 , 42.07134992, 49.28250588, 71.56674426,
       41.70562748, 44.70627972, 65.61703694, 39.19806175, 45.67

In [15]:
np.random.seed(42)
data = np.random.normal(loc=50,scale=10,size=1000)
data

array([54.96714153, 48.61735699, 56.47688538, 65.23029856, 47.65846625,
       47.65863043, 65.79212816, 57.67434729, 45.30525614, 55.42560044,
       45.36582307, 45.34270246, 52.41962272, 30.86719755, 32.75082167,
       44.37712471, 39.8716888 , 53.14247333, 40.91975924, 35.87696299,
       64.65648769, 47.742237  , 50.67528205, 35.75251814, 44.55617275,
       51.1092259 , 38.49006423, 53.75698018, 43.9936131 , 47.0830625 ,
       43.98293388, 68.52278185, 49.86502775, 39.42289071, 58.22544912,
       37.7915635 , 52.08863595, 30.40329876, 36.71813951, 51.96861236,
       57.3846658 , 51.71368281, 48.84351718, 46.98896304, 35.2147801 ,
       42.80155792, 45.39361229, 60.57122226, 53.4361829 , 32.36959845,
       53.24083969, 46.1491772 , 43.23078   , 56.11676289, 60.30999522,
       59.31280119, 41.60782477, 46.90787624, 53.31263431, 59.75545127,
       45.20825762, 48.14341023, 38.93665026, 38.03793376, 58.12525822,
       63.56240029, 49.27989878, 60.03532898, 53.61636025, 43.54

In [21]:
np.random.seed(42)
data = np.random.normal(loc=50,scale=10,size=1000)
data

array([54.96714153, 48.61735699, 56.47688538, 65.23029856, 47.65846625,
       47.65863043, 65.79212816, 57.67434729, 45.30525614, 55.42560044,
       45.36582307, 45.34270246, 52.41962272, 30.86719755, 32.75082167,
       44.37712471, 39.8716888 , 53.14247333, 40.91975924, 35.87696299,
       64.65648769, 47.742237  , 50.67528205, 35.75251814, 44.55617275,
       51.1092259 , 38.49006423, 53.75698018, 43.9936131 , 47.0830625 ,
       43.98293388, 68.52278185, 49.86502775, 39.42289071, 58.22544912,
       37.7915635 , 52.08863595, 30.40329876, 36.71813951, 51.96861236,
       57.3846658 , 51.71368281, 48.84351718, 46.98896304, 35.2147801 ,
       42.80155792, 45.39361229, 60.57122226, 53.4361829 , 32.36959845,
       53.24083969, 46.1491772 , 43.23078   , 56.11676289, 60.30999522,
       59.31280119, 41.60782477, 46.90787624, 53.31263431, 59.75545127,
       45.20825762, 48.14341023, 38.93665026, 38.03793376, 58.12525822,
       63.56240029, 49.27989878, 60.03532898, 53.61636025, 43.54

In [22]:
type(data)

numpy.ndarray

In [23]:
mean = np.mean(data)
median = np.median(data)
mode = stats.mode(data)

In [24]:
print(mean)
print(median)
print(mode)

50.193320558223256
50.25300612234888
ModeResult(mode=17.58732659930927, count=1)


In [25]:
# Hypothesis Testing [T-Test]
# H0 = Null Hypothesis - 95%
# H1 = Alternative Hypothesis - 5%
# Significance Level alpha (α), - 5% => p_value < 5% (α)
# df = degree of freedom (n-1) = sample size = 50 - 1 = 49
# p_value = probality value to either accept H0 or to reject H0
t_stat , p_value = stats.ttest_1samp(data,50)
print(t_stat)
print(p_value)

0.6243089585093229
0.5325672436623001


In [33]:
np.random.seed(77)
data = np.random.normal(loc=50,scale=10,size=1000)
data

array([52.24444852, 56.61531473, 44.20242361, 54.07811324, 54.66479367,
       30.252909  , 52.75548013, 34.24194827, 65.68396907, 42.75204977,
       53.05889717, 61.63942158, 39.5090461 , 40.23421994, 43.60949208,
       66.97429232, 37.13884699, 48.10838418, 49.26087332, 48.39504626,
       48.91206523, 43.03015986, 39.94189192, 46.07454951, 28.62206901,
       67.60930893, 42.25806773, 44.69766066, 42.06483989, 52.91902428,
       37.77994639, 34.30962235, 53.99950159, 49.54355307, 40.84080569,
       61.18986476, 51.9738121 , 52.75060112, 41.2086809 , 39.01760479,
       47.83229509, 39.67935649, 48.3161691 , 55.56938897, 58.12841843,
       48.72887915, 48.47722485, 50.70958812, 50.19954257, 38.79729891,
       32.72796017, 58.8876051 , 45.62196016, 43.58389665, 54.27464041,
       58.30527518, 60.8599978 , 48.62362342, 35.93038724, 61.59348124,
       40.08579994, 51.07351098, 44.55208737, 56.17910288, 79.08049021,
       66.69207801, 54.93889637, 47.27774554, 55.97619852, 48.94

In [34]:
t_stat , p_value = stats.ttest_1samp(data,50)
print(t_stat)
print(p_value)

-0.2930989936925345
0.7695073567246077


In [35]:
# Scikit-Learn
# Data Normalization
from sklearn.preprocessing import StandardScaler
dir(StandardScaler)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_reset',
 '_sklearn_auto_wrap_output_keys',
 '_validate_data',
 '_validate_params',
 'fit',
 'fit_transform',
 'get_feature_names_out',
 'get_metadata_routing',
 'get_params',
 'inverse_tr

In [36]:
data = np.random.normal(loc=50,scale=10,size=1000)
data = data.reshape(-1,1)
data

array([[45.11760225],
       [61.99530595],
       [46.01307735],
       [42.95783869],
       [36.73626502],
       [40.55359016],
       [49.18979998],
       [45.81156082],
       [49.44285129],
       [53.4340044 ],
       [60.48563987],
       [39.08963038],
       [40.39249543],
       [38.08978688],
       [48.64047701],
       [65.64711013],
       [47.9116196 ],
       [55.39911298],
       [57.72930159],
       [55.99665844],
       [66.83399833],
       [45.18121827],
       [39.19658654],
       [60.44499885],
       [53.75825155],
       [60.62590885],
       [55.89856545],
       [51.55072291],
       [57.17063083],
       [46.07952015],
       [38.98040437],
       [61.61545536],
       [36.46668068],
       [52.85235907],
       [50.26284006],
       [50.79399889],
       [49.7320836 ],
       [48.27440124],
       [58.56306769],
       [27.14964472],
       [37.34351412],
       [42.98928619],
       [57.8320177 ],
       [57.71853221],
       [35.93341608],
       [29

In [37]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[-4.97838378e-01],
       [ 1.18701738e+00],
       [-4.08445508e-01],
       [-7.13441764e-01],
       [-1.33452473e+00],
       [-9.53451427e-01],
       [-9.13218344e-02],
       [-4.28562361e-01],
       [-6.60604035e-02],
       [ 3.32365675e-01],
       [ 1.03631147e+00],
       [-1.09959459e+00],
       [-9.69533080e-01],
       [-1.19940628e+00],
       [-1.46159269e-01],
       [ 1.55156716e+00],
       [-2.18919143e-01],
       [ 5.28537177e-01],
       [ 7.61153637e-01],
       [ 5.88188533e-01],
       [ 1.67005102e+00],
       [-4.91487762e-01],
       [-1.08891745e+00],
       [ 1.03225439e+00],
       [ 3.64734395e-01],
       [ 1.05031415e+00],
       [ 5.78396174e-01],
       [ 1.44362750e-01],
       [ 7.05383038e-01],
       [-4.01812702e-01],
       [-1.11049833e+00],
       [ 1.14909791e+00],
       [-1.36143661e+00],
       [ 2.74301586e-01],
       [ 1.57968698e-02],
       [ 6.88210272e-02],
       [-3.71871194e-02],
       [-1.82703628e-01],
       [ 8.4

In [38]:
mean = np.mean(scaled_data)
median = np.median(scaled_data)
std = np.std(scaled_data)

print(mean)
print(median)
print(std)

-1.0658141036401503e-17
0.019958232865391626
1.0


In [40]:
# Polynomial Features
from sklearn.preprocessing import PolynomialFeatures
# X = np.random.rand(shape) 
X = np.random.rand(1000,1) * 10 # range (0,10)
poly = PolynomialFeatures(degree = 2)
X_poly = poly.fit_transform(X)
X_poly

array([[ 1.        ,  1.08905192,  1.18603408],
       [ 1.        ,  5.74000343, 32.9476394 ],
       [ 1.        ,  8.77327948, 76.97043285],
       ...,
       [ 1.        ,  0.93775867,  0.87939132],
       [ 1.        ,  6.49339568, 42.16418744],
       [ 1.        ,  2.35154546,  5.52976605]])

In [41]:
X

array([[1.08905192e+00],
       [5.74000343e+00],
       [8.77327948e+00],
       [3.22779793e+00],
       [6.32219841e-01],
       [6.40348730e+00],
       [8.30691272e+00],
       [2.00159399e+00],
       [6.61829642e+00],
       [6.01367461e+00],
       [8.17284854e-01],
       [2.29707590e+00],
       [6.23525406e+00],
       [9.41108367e+00],
       [7.47839522e+00],
       [4.81386622e+00],
       [2.05659509e+00],
       [1.06962350e-01],
       [1.53317228e+00],
       [1.52612423e+00],
       [5.67922931e+00],
       [3.34780487e+00],
       [3.86952160e+00],
       [2.14019548e+00],
       [9.54928263e-01],
       [6.76309186e+00],
       [4.35355247e+00],
       [3.20298731e+00],
       [8.84735511e+00],
       [5.51077035e+00],
       [8.59370563e+00],
       [6.57007104e+00],
       [7.26804011e+00],
       [1.38925633e+00],
       [5.89275912e+00],
       [8.02209401e+00],
       [5.74901399e+00],
       [8.36141029e+00],
       [3.00294845e-01],
       [5.51460036e+00],


In [42]:
mean = np.mean(X_poly)
median = np.median(X_poly)
std = np.std(X_poly)
print(mean)
print(median)
print(std)

13.044651091712142
3.3515809003514176
22.102341307163584


In [43]:
# Polynomial Features [degree = 3]
from sklearn.preprocessing import PolynomialFeatures
# X = np.random.rand(shape) 
X = np.random.rand(1000,1) * 10 # range (0,10)
poly = PolynomialFeatures(degree = 3)
X_poly = poly.fit_transform(X)
X_poly

array([[1.00000000e+00, 9.61087594e+00, 9.23689364e+01, 8.87746388e+02],
       [1.00000000e+00, 1.45902699e-01, 2.12875975e-02, 3.10591792e-03],
       [1.00000000e+00, 9.67301669e+00, 9.35672518e+01, 9.05077588e+02],
       ...,
       [1.00000000e+00, 2.68416700e-01, 7.20475251e-02, 1.93387590e-02],
       [1.00000000e+00, 2.27904414e+00, 5.19404220e+00, 1.18374515e+01],
       [1.00000000e+00, 5.25202331e+00, 2.75837488e+01, 1.44870492e+02]])

In [44]:
mean = np.mean(X_poly)
median = np.median(X_poly)
std = np.std(X_poly)
print(mean)
print(median)
print(std)

67.65887452819575
5.3855629342957965
168.86457585067956


In [46]:
# StatsModel
import pandas as pd
import statsmodels.api as sm
dir(sm.stats)

['AnovaRM',
 'CompareMeans',
 'DescrStatsW',
 'Describe',
 'FTestAnovaPower',
 'FTestPower',
 'FactoredPSDMatrix',
 'GofChisquarePower',
 'Mediation',
 'NormalIndPower',
 'NullDistribution',
 'OaxacaBlinder',
 'RegressionFDR',
 'Runs',
 'SquareTable',
 'StratifiedTable',
 'TTestIndPower',
 'TTestPower',
 'Table',
 'Table2x2',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acorr_breusch_godfrey',
 'acorr_ljungbox',
 'acorr_lm',
 'anova_generic',
 'anova_lm',
 'anova_oneway',
 'binom_test',
 'binom_test_reject_interval',
 'binom_tost',
 'binom_tost_reject_interval',
 'breaks_cusumolsresid',
 'breaks_hansen',
 'chisquare_effectsize',
 'cochrans_q',
 'cohens_kappa',
 'combine_effects',
 'compare_cox',
 'compare_encompassing',
 'compare_j',
 'confint_effectsize_oneway',
 'confint_mvmean',
 'confint_mvmean_fromstats',
 'confint_noncentrality',
 'confint_poisson',
 'confint_poisson_2indep',
 'confint_proportions_

In [47]:
data = np.random.normal(loc=50,scale=10,size=1000)
df = pd.DataFrame(data, columns = ['Value'])
df

,Value
0,56.597539
1,47.913522
2,35.476874
3,48.151112
4,41.503609
...,...
995,42.922185
996,34.728729
997,40.790370
998,63.534198


In [48]:
stats_model = sm.stats.DescrStatsW(df['Value'])
stats_model

In [49]:
mean = stats_model.mean
median = df['Value'].median()
print(mean)
print(median)

50.051062143564224
49.75379675853475
