In [1]:
# Importing all the dependencies requried for the Case Study ...
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
match_df = pd.read_csv("DS_match.csv")
match_df.head(10)

,Unnamed: 0,match_id,match_number,date,start_time,result,player_id_of_the_match,player_name_of_the_match,series_id,series_name,status,toss_winner,toss_selection,venue_id,venue_name,home_team_id,home_team_name
0,0,1,Match 1,7/26/2014,20:00,U Mumba beat Jaipur Pink Panthers (45 - 31),29.0,29.0,1,"Pro Kabaddi League Season 1, 2014",Full Time,5,Choice of court : Right,5,"DOME@NSCI SVP Stadium, Mumbai",5.0,U Mumba
1,1,10,Match 10,7/31/2014,21:00,Bengal Warriors beat Dabang Delhi (42 - 40),12.0,12.0,1,"Pro Kabaddi League Season 1, 2014",Full Time,2,Choice of court : Left,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",4.0,Bengal Warriors
2,2,100,Match 39,8/9/2015,21:00,Dabang Delhi beat Patna Pirates (45-26),58.0,58.0,2,"Pro Kabaddi League, 2015",Full Time,6,Choice of court :Left,2,"Thyagaraj Sports Complex, Delhi",NaN,NaN
3,3,101,Match 40,8/10/2015,20:00,Jaipur Pink Panthers beat Dabang Delhi (51-21),NaN,NaN,2,"Pro Kabaddi League, 2015",Full Time,3,Choice of court :Left,2,"Thyagaraj Sports Complex, Delhi",NaN,NaN
4,4,102,Match 41,8/11/2015,20:00,Jaipur Pink Panthers beat Puneri Paltan (31-18),86.0,86.0,2,"Pro Kabaddi League, 2015",Full Time,7,Choice of court :Left,2,"Thyagaraj Sports Complex, Delhi",NaN,NaN
5,5,103,Match 42,8/11/2015,21:00,Match Tied,58.0,58.0,2,"Pro Kabaddi League, 2015",Full Time,8,Choice of court :Right,2,"Thyagaraj Sports Complex, Delhi",NaN,NaN
6,6,104,Match 43,8/12/2015,20:00,U Mumba beat Bengaluru Bulls (36-29),94.0,94.0,2,"Pro Kabaddi League, 2015",Full Time,1,Choice of court :Right,1,"Sree Kanteerava Stadium, Bengaluru",NaN,NaN
7,7,105,Match 44,8/13/2015,20:00,Bengal Warriors beat Puneri Paltan (31-28),141.0,141.0,2,"Pro Kabaddi League, 2015",Full Time,7,Choice of court :Left,1,"Sree Kanteerava Stadium, Bengaluru",NaN,NaN
8,8,1050,Match 11,10/12/2018,20:00,Match Tied,NaN,NaN,32,"Testing Pro Kabaddi League Season 6, 2018",Full Time,28,Choice of court :Left,14,"Motilal Nehru School of Sports, Rai, Sonepat",28.0,Haryana Steelers
9,9,1051,Match 15,10/14/2018,20:00,NaN,NaN,NaN,32,"Testing Pro Kabaddi League Season 6, 2018",2nd Half,6,Choice of court :Left,14,"Motilal Nehru School of Sports, Rai, Sonepat",NaN,NaN


In [7]:
match_df.shape

(684, 17)

In [8]:
match_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 684 entries, 0 to 683
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                684 non-null    int64  
 1   match_id                  684 non-null    int64  
 2   match_number              684 non-null    object 
 3   date                      684 non-null    object 
 4   start_time                684 non-null    object 
 5   result                    679 non-null    object 
 6   player_id_of_the_match    575 non-null    float64
 7   player_name_of_the_match  575 non-null    float64
 8   series_id                 684 non-null    int64  
 9   series_name               684 non-null    object 
 10  status                    684 non-null    object 
 11  toss_winner               684 non-null    int64  
 12  toss_selection            684 non-null    object 
 13  venue_id                  684 non-null    int64  
 14  venue_name

In [9]:
players_df = pd.read_csv('DS_players.csv')
players_df.head(10)

,Unnamed: 0,index,player_id,player_name,player_short_name,player_skill,player_role,player_red_card,player_yellow_card,player_green_card,...,player_tackle_points_capture_bonus,player_raids_total,player_raids_successful,player_raids_unsuccessful,player_raids_Empty,player_tackles_total,player_tackles_successful,player_tackles_unsuccessful,match_id,team_id
0,0,0,15,Sanjay Shrestha,Sanjay Shrestha,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3
1,0,0,96,Rohit Rana,Rohit Rana,NaN,NaN,False,False,False,...,0,1,0,0,1,0,0,0,1,3
2,0,0,72,Navneet Gautam,Navneet Gautam,NaN,NaN,False,False,False,...,0,1,0,0,1,0,0,0,1,3
3,0,0,52,Jasvir Singh,Jasvir Singh,NaN,NaN,False,False,False,...,1,12,7,3,2,10,3,7,1,3
4,0,0,22,Wei Yang,Wei Yang,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3
5,0,0,144,Gokul Shitole,Gokul Shitole,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3
6,0,0,147,Prashant Chavan,Prashant Chavan,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3
7,0,0,32,Balbir Singh,Balbir Singh,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3
8,0,0,44,Gangadhari Mallesh,Gangadhari Mallesh,NaN,NaN,False,False,False,...,0,3,3,0,0,2,0,2,1,3
9,0,0,87,Raju Lal Choudhary,Raju Lal Choudhary,NaN,NaN,False,False,False,...,0,0,0,0,0,0,0,0,1,3


In [10]:
players_df.shape

(16892, 31)

In [12]:
players_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16892 entries, 0 to 16891
Data columns (total 31 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   Unnamed: 0                          16892 non-null  int64  
 1   index                               16892 non-null  int64  
 2   player_id                           16892 non-null  int64  
 3   player_name                         16892 non-null  object 
 4   player_short_name                   1698 non-null   object 
 5   player_skill                        0 non-null      float64
 6   player_role                         0 non-null      float64
 7   player_red_card                     16892 non-null  bool   
 8   player_yellow_card                  16892 non-null  bool   
 9   player_green_card                   16892 non-null  bool   
 10  player_jersey                       16892 non-null  int64  
 11  player_played                       16892

In [17]:
team_df = pd.read_csv('DS_team.csv',low_memory = False)
team_df.head(10)

,Unnamed: 0,id,match_id,name,score,short_name,squad,state_of_play,state_of_play.is_raiding_now,state_of_play.last_raid.id,...,stats.points.total,stats.raids.Empty,stats.raids.successful,stats.raids.super_raids,stats.raids.total,stats.raids.unsuccessful,stats.tackles.successful,stats.tackles.super_tackles,stats.tackles.total,stats.tackles.unsuccessful
0,0,3,1,Jaipur Pink Panthers,28,JAI,"[{'id': 15, 'name': 'Sanjay Shrestha', 'short_...",NaN,False,0.0,...,28,10,20,NaN,40,10,1,NaN,24,23
1,1,5,1,U Mumba,44,MUM,"[{'id': 54, 'name': 'Jeeva Kumar', 'short_name...",NaN,False,0.0,...,44,15,21,NaN,40,4,10,NaN,32,22
2,0,2,10,Dabang Delhi K.C.,39,DEL,"[{'id': 4, 'name': 'Ehsan Zamani Fard', 'short...",NaN,False,0.0,...,39,8,24,NaN,44,12,8,NaN,27,19
3,1,4,10,Bengal Warriors,40,KOL,"[{'id': 5, 'name': 'Farhad Kamal Gharibi', 'sh...",NaN,False,0.0,...,40,20,16,NaN,45,9,11,NaN,32,21
4,0,2,100,Dabang Delhi,45,DEL,"[{'id': 58, 'name': 'Kashiling Adake', 'short_...",NaN,NaN,NaN,...,45,25,13,NaN,45,7,13,NaN,25,12
5,1,6,100,Patna Pirates,26,PAT,"[{'id': 142, 'name': 'Sandeep Narwal', 'short_...",NaN,NaN,NaN,...,26,15,15,NaN,44,14,6,NaN,28,22
6,0,2,101,Dabang Delhi,21,DEL,"[{'id': 58, 'name': 'Kashiling Adake', 'short_...",NaN,NaN,NaN,...,21,16,10,NaN,39,13,6,NaN,33,27
7,1,3,101,Jaipur Pink Panthers,51,JAI,"[{'id': 160, 'name': 'Ran Singh', 'short_name'...",NaN,NaN,NaN,...,51,16,18,NaN,40,6,12,NaN,21,9
8,0,3,102,Jaipur Pink Panthers,31,JAI,"[{'id': 86, 'name': 'Rajesh Narwal', 'short_na...",NaN,NaN,NaN,...,31,24,14,NaN,44,6,12,NaN,21,9
9,1,7,102,Puneri Paltan,18,PUN,"[{'id': 67, 'name': 'Mahipal Narwal', 'short_n...",NaN,NaN,NaN,...,18,22,10,NaN,44,12,6,NaN,21,15


In [18]:
team_df.shape

(1368, 34)

In [19]:
team_df.shape[0]/2

684.0

In [20]:
team_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1368 entries, 0 to 1367
Data columns (total 34 columns):
 #   Column                                    Non-Null Count  Dtype  
---  ------                                    --------------  -----  
 0   Unnamed: 0                                1368 non-null   int64  
 1   id                                        1368 non-null   int64  
 2   match_id                                  1368 non-null   int64  
 3   name                                      1368 non-null   object 
 4   score                                     1368 non-null   int64  
 5   short_name                                1368 non-null   object 
 6   squad                                     1368 non-null   object 
 7   state_of_play                             0 non-null      float64
 8   state_of_play.is_raiding_now              596 non-null    object 
 9   state_of_play.last_raid.id                596 non-null    float64
 10  state_of_play.last_raid.result      

In [3]:
events_df = pd.read_csv("DS_events.csv", low_memory = False)
events_df.head(10)

,Column1,clock,defender_id,defenders,defending_all_out_points,defending_bonus_points,defending_capture_points,defending_points,defending_team_id,defending_technical_points,...,review.reason.id,review.reason.reason_value,review.review_taken,review.team_id,score,status_id,substituted_by,super_raid,super_tackle,team_id
0,0,0:33,NaN,NaN,NaN,NaN,NaN,0.0,5.0,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
1,1,0:43,NaN,NaN,NaN,NaN,NaN,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
2,2,0:48,54.0,NaN,NaN,NaN,NaN,1.0,5.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 2]",0.0,NaN,NaN,NaN,NaN
3,3,1:42,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
4,4,2:19,NaN,NaN,NaN,NaN,NaN,0.0,5.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
5,5,2:48,NaN,NaN,NaN,NaN,NaN,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
6,6,3:10,NaN,NaN,NaN,NaN,NaN,0.0,5.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
7,7,3:45,147.0,NaN,NaN,NaN,NaN,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,"[3, 3]",0.0,NaN,NaN,NaN,NaN
8,8,3:45,96.0,NaN,NaN,NaN,NaN,0.0,3.0,NaN,...,NaN,NaN,NaN,NaN,"[3, 3]",0.0,NaN,NaN,NaN,NaN
9,9,4:8,123.0,NaN,NaN,NaN,NaN,1.0,5.0,NaN,...,NaN,NaN,NaN,NaN,"[4, 3]",0.0,NaN,NaN,NaN,NaN


In [21]:
events_df.shape

(66568, 41)

In [22]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66568 entries, 0 to 66567
Data columns (total 41 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Column1                       66568 non-null  int64  
 1   clock                         66568 non-null  object 
 2   defender_id                   14055 non-null  float64
 3   defenders                     0 non-null      float64
 4   defending_all_out_points      19799 non-null  float64
 5   defending_bonus_points        19799 non-null  float64
 6   defending_capture_points      19799 non-null  float64
 7   defending_points              58315 non-null  float64
 8   defending_team_id             58315 non-null  float64
 9   defending_technical_points    19799 non-null  float64
 10  do_or_die                     20297 non-null  object 
 11  event                         66568 non-null  object 
 12  event_id                      66568 non-null  int64  
 13  e

In [23]:
events_df['event'].unique()

array(['Successful Raid', 'Empty Raid', 'Unsuccessful Raid',
       'Substitution', 'Raider and Anti Out', 'TimeOut', 'Green Card',
       'Non Raid Technical Points', 'Yellow Card', 'Red Card'],
      dtype=object)

In [24]:
events_df['event'].value_counts()

event
Empty Raid                   24951
Successful Raid              20218
Unsuccessful Raid            13119
Substitution                  4733
TimeOut                       2588
Green Card                     657
Non Raid Technical Points      224
Yellow Card                     48
Raider and Anti Out             27
Red Card                         3
Name: count, dtype: int64

In [25]:
events_df[events_df['event'] == 'Substitution'][['clock','event','event_text','match_id','player_id']]

,clock,event,event_text,match_id,player_id
34,16:4,Substitution,Gangadhari Mallesh comes in for Prashant Chavan,1,147.0
45,20:0,Substitution,Balbir Singh comes in for Gangadhari Mallesh,1,44.0
58,25:1,Substitution,Gangadhari Mallesh comes in for Gokul Shitole,1,144.0
205,07:10,Substitution,Varinder Singh comes in for Vijay Malik,100,208.0
207,07:29,Substitution,Vijay Malik comes in for Varinder Singh,100,260.0
...,...,...,...,...,...
66521,21:02,Substitution,Deepak Kumar comes in for Kedar Lal,99,184.0
66528,24:03,Substitution,Bajirao Hodage comes in for Vikas Kale,99,164.0
66533,26:01,Substitution,Vineet Sharma comes in for Jang Kun Lee,99,268.0
66544,31:05,Substitution,Mahendra Ganesh Rajput comes in for Deepak Kumar,99,163.0


In [27]:
events_df[events_df['event'] == 'Successful Raid'][['clock','event','event_text','match_id','raid_points']]

,clock,event,event_text,match_id,raid_points
0,0:33,Successful Raid,Jasvir Singh Successful Raid,1,1.0
7,3:45,Successful Raid,Shabeer Bappu Successful Raid,1,2.0
8,3:45,Successful Raid,Shabeer Bappu Successful Raid,1,2.0
10,4:28,Successful Raid,Anup Kumar Successful Raid,1,1.0
11,5:19,Successful Raid,Jasvir Singh Successful Raid,1,2.0
...,...,...,...,...,...
66549,32:58,Successful Raid,Pradeep Kumar raids successfully,99,1.0
66556,36:00,Successful Raid,Bhupender Singh raids successfully,99,1.0
66559,36:44,Successful Raid,Anup Kumar raids successfully,99,3.0
66562,37:36,Successful Raid,Pradeep Kumar raids successfully,99,1.0


In [29]:
events_df[events_df['event']=='Unsuccessful Raid'][['clock','event','event_text','defending_points','defender_id']]

,clock,event,event_text,defending_points,defender_id
2,0:48,Unsuccessful Raid,Maninder Singh Unsuccessful Raid,1.0,54.0
3,1:42,Unsuccessful Raid,Anup Kumar Unsuccessful Raid,1.0,NaN
9,4:8,Unsuccessful Raid,Maninder Singh Unsuccessful Raid,1.0,123.0
15,7:5,Unsuccessful Raid,Anup Kumar Unsuccessful Raid,1.0,NaN
18,8:44,Unsuccessful Raid,Maninder Singh Unsuccessful Raid,1.0,146.0
...,...,...,...,...,...
66555,35:18,Unsuccessful Raid,Kedar Lal Unsuccessful Raid,1.0,NaN
66557,36:13,Unsuccessful Raid,Deepak Kumar Unsuccessful Raid,1.0,71.0
66561,37:23,Unsuccessful Raid,Kedar Lal Unsuccessful Raid,1.0,NaN
66566,39:41,Unsuccessful Raid,Bhupender Singh Unsuccessful Raid,1.0,108.0


In [33]:
# Identify Missing Values
events_df.isnull().sum().sort_values(ascending = False)

reason_id                       66568
defenders                       66568
review.outcome                  66568
review.reason                   66568
review.reason.reason_value      66125
review.reason.id                66125
review.outcome.id               66125
review.outcome.outcome_value    66125
raider_bonus                    66070
reason                          65646
substituted_by                  61835
player_id                       61127
team_id                         58318
defender_id                     52513
raid_touch_points               46769
review.review_taken             46769
review.team_id                  46769
super_raid                      46769
super_tackle                    46769
raid_technical_points           46769
raid_bonus_points               46769
raid_all_out_points             46769
defending_all_out_points        46769
defending_bonus_points          46769
defending_capture_points        46769
defending_technical_points      46769
do_or_die   

In [34]:
# .describe # Statisitcal Analysis
events_df.describe() # default -> Numerical Columns

,Column1,defender_id,defenders,defending_all_out_points,defending_bonus_points,defending_capture_points,defending_points,defending_team_id,defending_technical_points,event_id,...,raiding_team_id,reason_id,review.outcome,review.outcome.id,review.reason,review.reason.id,review.team_id,status_id,substituted_by,team_id
count,66568.000000,14055.000000,0.0,19799.000000,19799.000000,19799.000000,58315.000000,58315.000000,19799.000000,66568.000000,...,58315.000000,0.0,0.0,443.000000,0.0,443.000000,19799.000000,45112.000000,4733.000000,8250.000000
mean,48.710326,386.817645,NaN,0.028486,0.021112,0.218950,0.271885,14.574415,0.016617,2.607199,...,14.569682,NaN,NaN,1.641084,NaN,39.690745,0.464670,1.541231,619.011409,11.677212
std,28.798869,557.652491,NaN,0.236989,0.143762,0.413545,0.563008,31.458682,0.139547,1.714135,...,31.451141,NaN,NaN,0.480225,NaN,2.621971,7.246936,2.455353,772.152368,26.650550
min,0.000000,4.000000,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,...,1.000000,NaN,NaN,1.000000,NaN,37.000000,0.000000,0.000000,4.000000,0.000000
25%,24.000000,96.000000,NaN,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,...,3.000000,NaN,NaN,1.000000,NaN,37.000000,0.000000,0.000000,156.000000,1.000000
50%,48.000000,179.000000,NaN,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,2.000000,...,6.000000,NaN,NaN,2.000000,NaN,39.000000,0.000000,2.000000,293.000000,5.000000
75%,73.000000,401.000000,NaN,0.000000,0.000000,0.000000,0.000000,16.000000,0.000000,3.000000,...,16.000000,NaN,NaN,2.000000,NaN,43.000000,0.000000,3.000000,689.000000,9.000000
max,122.000000,2672.000000,NaN,2.000000,1.000000,1.000000,3.000000,243.000000,2.000000,11.000000,...,243.000000,NaN,NaN,2.000000,NaN,44.000000,243.000000,19.000000,2683.000000,243.000000


In [35]:
events_df.describe(include = 'all') # Categorical + Numerical

,Column1,clock,defender_id,defenders,defending_all_out_points,defending_bonus_points,defending_capture_points,defending_points,defending_team_id,defending_technical_points,...,review.reason.id,review.reason.reason_value,review.review_taken,review.team_id,score,status_id,substituted_by,super_raid,super_tackle,team_id
count,66568.000000,66568,14055.000000,0.0,19799.000000,19799.000000,19799.000000,58315.000000,58315.000000,19799.000000,...,443.000000,443,19799,19799.000000,59233,45112.000000,4733.000000,19799,19799,8250.000000
unique,NaN,3212,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8,2,NaN,2438,NaN,NaN,2,2,NaN
top,NaN,19:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Touches,False,NaN,"[0, 0]",NaN,NaN,False,False,NaN
freq,NaN,303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,153,19356,NaN,795,NaN,NaN,19574,19350,NaN
mean,48.710326,NaN,386.817645,NaN,0.028486,0.021112,0.218950,0.271885,14.574415,0.016617,...,39.690745,NaN,NaN,0.464670,NaN,1.541231,619.011409,NaN,NaN,11.677212
std,28.798869,NaN,557.652491,NaN,0.236989,0.143762,0.413545,0.563008,31.458682,0.139547,...,2.621971,NaN,NaN,7.246936,NaN,2.455353,772.152368,NaN,NaN,26.650550
min,0.000000,NaN,4.000000,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,37.000000,NaN,NaN,0.000000,NaN,0.000000,4.000000,NaN,NaN,0.000000
25%,24.000000,NaN,96.000000,NaN,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,...,37.000000,NaN,NaN,0.000000,NaN,0.000000,156.000000,NaN,NaN,1.000000
50%,48.000000,NaN,179.000000,NaN,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,...,39.000000,NaN,NaN,0.000000,NaN,2.000000,293.000000,NaN,NaN,5.000000
75%,73.000000,NaN,401.000000,NaN,0.000000,0.000000,0.000000,0.000000,16.000000,0.000000,...,43.000000,NaN,NaN,0.000000,NaN,3.000000,689.000000,NaN,NaN,9.000000


In [36]:
events_df.nunique()

Column1                          123
clock                           3212
defender_id                      536
defenders                          0
defending_all_out_points           2
defending_bonus_points             2
defending_capture_points           2
defending_points                   4
defending_team_id                 45
defending_technical_points         3
do_or_die                          2
event                             10
event_id                          10
event_no                         123
event_text                      5413
match_id                         684
player_id                        610
raid_all_out_points                2
raid_bonus_points                  2
raid_points                       12
raid_technical_points              5
raid_touch_points                  6
raider_bonus                       2
raider_id                        631
raiding_team_id                   45
reason                            20
reason_id                          0
r

In [37]:
# Data Cleaning
# -> Fix Data Types, Removing Duplicates , Missing Values , Inconsistent Text
# Converting the Data Types
events_df.dtypes

Column1                           int64
clock                            object
defender_id                     float64
defenders                       float64
defending_all_out_points        float64
defending_bonus_points          float64
defending_capture_points        float64
defending_points                float64
defending_team_id               float64
defending_technical_points      float64
do_or_die                        object
event                            object
event_id                          int64
event_no                          int64
event_text                       object
match_id                          int64
player_id                       float64
raid_all_out_points             float64
raid_bonus_points               float64
raid_points                     float64
raid_technical_points           float64
raid_touch_points               float64
raider_bonus                    float64
raider_id                       float64
raiding_team_id                 float64


In [38]:
events_df['do_or_die'].unique()

array([nan, False, True], dtype=object)

In [39]:
events_df['reason'].unique()

array([nan, 'Pulling of clothes', 'Other', 'Arguing with officials',
       'Failed to start raid within 5 seconds', 'Dangerous play',
       'Dissent', 'More than one raid', 'Improper holding',
       'Raider warned or instructed by teammates', 'Reckless foul',
       'Excessive / unnecessary violence',
       'Raiding team player crosses boundary', 'Misconduct',
       'Player leaves court during suspension of game', 'Injuring',
       'Yellow card awarded to the coach', 'Improper Holding',
       'Disturbance in play', 'Deliberate time wasting tactics',
       'Time Out violation'], dtype=object)

In [40]:
events_df['review.outcome.outcome_value'].unique()

array([nan, 'Unsuccessful', 'Successful'], dtype=object)

In [41]:
events_df['review.outcome'].unique()

array([nan])

In [42]:
events_df['score'].unique()

array(['[0, 1]', '[1, 2]', '[1, 3]', ..., '[52, 27]', '[52, 28]',
       '[52, 30]'], dtype=object)

In [43]:
events_df['super_raid'].unique()

array([nan, False, True], dtype=object)

In [44]:
events_df['super_tackle'].unique()

array([nan, False, True], dtype=object)

In [46]:
# Removing Duplicates:
print("Duplicates Before: " , events_df.duplicated().sum())
events_df = events_df.drop_duplicates()
print("Duplicates After: " , events_df.duplicated().sum())

Duplicates Before:  0
Duplicates After:  0


In [48]:
events_df.shape

(66568, 41)

In [49]:
# Dropping the fully Null Columns
events_df.dropna(axis = 1, how = 'all' , inplace = True)
events_df.shape

(66568, 37)

In [50]:
events_df.head(5)

,Column1,clock,defender_id,defending_all_out_points,defending_bonus_points,defending_capture_points,defending_points,defending_team_id,defending_technical_points,do_or_die,...,review.reason.id,review.reason.reason_value,review.review_taken,review.team_id,score,status_id,substituted_by,super_raid,super_tackle,team_id
0,0,0:33,NaN,NaN,NaN,NaN,0.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
1,1,0:43,NaN,NaN,NaN,NaN,0.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
2,2,0:48,54.0,NaN,NaN,NaN,1.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,"[1, 2]",0.0,NaN,NaN,NaN,NaN
3,3,1:42,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
4,4,2:19,NaN,NaN,NaN,NaN,0.0,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN


In [51]:
events_df['defending_all_out_points'].unique()

array([nan,  0.,  2.])

In [52]:
events_df['defending_bonus_points'].unique()

array([nan,  0.,  1.])

In [53]:
events_df['defending_capture_points'].unique()

array([nan,  0.,  1.])

In [54]:
events_df['defending_points'].unique()

array([ 0.,  1., nan,  2.,  3.])

In [55]:
events_df.columns

Index(['Column1', 'clock', 'defender_id', 'defending_all_out_points',
       'defending_bonus_points', 'defending_capture_points',
       'defending_points', 'defending_team_id', 'defending_technical_points',
       'do_or_die', 'event', 'event_id', 'event_no', 'event_text', 'match_id',
       'player_id', 'raid_all_out_points', 'raid_bonus_points', 'raid_points',
       'raid_technical_points', 'raid_touch_points', 'raider_bonus',
       'raider_id', 'raiding_team_id', 'reason', 'review.outcome.id',
       'review.outcome.outcome_value', 'review.reason.id',
       'review.reason.reason_value', 'review.review_taken', 'review.team_id',
       'score', 'status_id', 'substituted_by', 'super_raid', 'super_tackle',
       'team_id'],
      dtype='object')

In [58]:
events_df.columns[-1]

'team_id'

In [59]:
type(events_df.columns[-1])

str

In [56]:
# Handling Missing values by recognizing common patterns 
# Pattern - 1 : ['points'] columns -> fillna(0)

points_cols = [col for col in events_df.columns if col.endswith('points')]
points_cols

['defending_all_out_points',
 'defending_bonus_points',
 'defending_capture_points',
 'defending_points',
 'defending_technical_points',
 'raid_all_out_points',
 'raid_bonus_points',
 'raid_points',
 'raid_technical_points',
 'raid_touch_points']

In [57]:
len(points_cols)

10

In [61]:
# Long Hand:
point_cols = []
for col in events_df.columns:
    if col.endswith('points'):
        point_cols.append(col)

point_cols

['defending_all_out_points',
 'defending_bonus_points',
 'defending_capture_points',
 'defending_points',
 'defending_technical_points',
 'raid_all_out_points',
 'raid_bonus_points',
 'raid_points',
 'raid_technical_points',
 'raid_touch_points']

In [63]:
# Identifying missing Values on 'points' cols
events_df[point_cols].isnull().sum()

defending_all_out_points      46769
defending_bonus_points        46769
defending_capture_points      46769
defending_points               8253
defending_technical_points    46769
raid_all_out_points           46769
raid_bonus_points             46769
raid_points                    8253
raid_technical_points         46769
raid_touch_points             46769
dtype: int64

In [64]:
# LHS = RHS [Handling Missing Values]
events_df[point_cols] = events_df[point_cols].fillna(0)

In [65]:
# After
# Identifying missing Values on 'points' cols
events_df[point_cols].isnull().sum()

defending_all_out_points      0
defending_bonus_points        0
defending_capture_points      0
defending_points              0
defending_technical_points    0
raid_all_out_points           0
raid_bonus_points             0
raid_points                   0
raid_technical_points         0
raid_touch_points             0
dtype: int64

In [66]:
events_df.head(5)

,Column1,clock,defender_id,defending_all_out_points,defending_bonus_points,defending_capture_points,defending_points,defending_team_id,defending_technical_points,do_or_die,...,review.reason.id,review.reason.reason_value,review.review_taken,review.team_id,score,status_id,substituted_by,super_raid,super_tackle,team_id
0,0,0:33,NaN,0.0,0.0,0.0,0.0,5.0,0.0,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
1,1,0:43,NaN,0.0,0.0,0.0,0.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,"[0, 1]",0.0,NaN,NaN,NaN,NaN
2,2,0:48,54.0,0.0,0.0,0.0,1.0,5.0,0.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 2]",0.0,NaN,NaN,NaN,NaN
3,3,1:42,NaN,0.0,0.0,0.0,1.0,3.0,0.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
4,4,2:19,NaN,0.0,0.0,0.0,0.0,5.0,0.0,NaN,...,NaN,NaN,NaN,NaN,"[1, 3]",0.0,NaN,NaN,NaN,NaN
