In [3]:
!pip3 install numpy

In [4]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [5]:
np.__version__

'1.26.4'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [8]:
# num = np.array(<Iterable>)
num = np.array([11,22,33,44,55,66,77,88,99])
num

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [9]:
print(num)

[11 22 33 44 55 66 77 88 99]


In [10]:
# Indexation in numpy : start with 0
num[0]

11

In [11]:
num[6]# 77 

77

In [12]:
num[-1] # 99

99

In [13]:
arr_from_list = np.array([11,22,33,44,55,66,77,88,99])
arr_from_tuple = np.array((11,22,33,44,55,66,77,88,99))
print(arr_from_list)
print(arr_from_tuple)

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]


In [15]:
np_arr = np.array(11) 
np_arr

array(11)

In [16]:
print(np_arr)

11


In [17]:
type(arr_from_list)

numpy.ndarray

In [18]:
# ndarray -> N Dimensional Array
print(type(arr_from_list)) # class <numpy.ndarray>

<class 'numpy.ndarray'>


In [19]:
# Properties [ndim]
# print("Hello World" , end = " ") -> end -> attribute
arr_from_list.ndim

1

In [20]:
# np_arr # 11
np_arr.ndim # 0

0

In [21]:
# 1D Array 
# Numpy -> An array object of arbitrary homogeneous items
arr_1d = np.array([11,121.9,True,'k','Coding',11+5j,99]) # Mixed Type [Upcasting]
print(arr_1d)

['11' '121.9' 'True' 'k' 'Coding' '(11+5j)' '99']


In [22]:
type(arr_1d)

numpy.ndarray

In [23]:
arr_1d.dtype # property data type

dtype('<U64')

In [24]:
arr_1d.ndim

1

In [25]:
# 2D Array [2 Dimensional] [row * col] n*m (5,3)
# Numpy -> An array object of arbitrary homogeneous items
arr_2d = np.array([
    [11,22,33],
    ['a','b','c'],
    [True,False,True],
    ['learn','python','programming'],
    [9.99,11.11,12.99]
]) # Mixed Type [Heterogenous] 
print(arr_2d)

[['11' '22' '33']
 ['a' 'b' 'c']
 ['True' 'False' 'True']
 ['learn' 'python' 'programming']
 ['9.99' '11.11' '12.99']]


In [26]:
type(arr_2d)

numpy.ndarray

In [27]:
arr_2d.ndim # property

2

In [30]:
# 3D [3 Dimensional] [Depth,row,col] (d*r*c) = Total Number of Elements
# 3 Depth , 3 Rows , 3 Cols = 27
arr_3d = np.array([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],

    [[1.1,2.1,3.1],
    [4.1,5.1,6.1],
    [7.1,8.1,9.1]],

    [[False,True,True],
    [True,False,True],
    [False,True,False]],
]) # 'upcasting' -> 'float'
arr_3d

array([[[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1.1, 2.1, 3.1],
        [4.1, 5.1, 6.1],
        [7.1, 8.1, 9.1]],

       [[0. , 1. , 1. ],
        [1. , 0. , 1. ],
        [0. , 1. , 0. ]]])

In [31]:
type(arr_3d)

numpy.ndarray

In [32]:
arr_3d.ndim # n- dimension [3D]

3

In [33]:
# 27 => 3*3*3
# 1D -> 3D 
arr_1d = np.array([1,2,3,4,5,6,7,8,9,'a','b','c','d','e','f','g','h','i',9,8,7,6,5,4,3,2,1])
arr_1d

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd',
       'e', 'f', 'g', 'h', 'i', '9', '8', '7', '6', '5', '4', '3', '2',
       '1'], dtype='<U11')

In [34]:
# 3D Shape [3,3,3] -> depth-> 3 , row -> 3 , cols -> 3
arr_1d.reshape(3,3,3)

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']],

       [['a', 'b', 'c'],
        ['d', 'e', 'f'],
        ['g', 'h', 'i']],

       [['9', '8', '7'],
        ['6', '5', '4'],
        ['3', '2', '1']]], dtype='<U11')

In [35]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [36]:
# 1D -> 2D
# 4*4 , 8*2, 2*8
arr_1d.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr_1d.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [39]:
arr_1d.reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [40]:
# 3D -> 2*4*2 , 2*2*4, 1*4*4
arr_1d.reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [41]:
arr_1d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [43]:
# 4D -> 2*2*2*2 # 3D[depth,rows,cols]
arr_4d = arr_1d.reshape(2,2,2,2) # 4D -> 2 depth of 3D
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [44]:
arr_4d.ndim # property

4